# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C4oPIHPyShvu5Jv1u5fcx4pamBQuiv8t
"""

x=5
print(f"變數的值是：{x}")
print(f"變數的記憶體位址是：{id(x)}")